gucc/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include,path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('gucc_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gucc_app/urls.py
from django.urls import path

from . import views

app_name = 'gucc_app'   

urlpatterns = [
    path('', views.index, name='index'), 
    path('about/', views.about, name='about'),
    path('committee/', views.committee, name='committee'),
    path('welfare', views.welfare, name='welfare'),
    path('events/', views.events, name='events'),
    path('gallery/', views.gallery, name='gallery'),
    path('main-shed/', views.main_shed, name='main_shed'),
    path('macpherson-shed/', views.macpherson_shed, name='macpherson_shed'),
    path('profile/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('koalas/', views.koalas, name='koalas'),
    path('basekit/', views.basekit, name='basekit'),
    path('kayakkit/', views.kayakkit, name='kayakkit'),
    path('baseinventory/', views.baseinventory, name='baseinventory'),
    path('test/', views.test, name='test'),
    path('pool/', views.pool, name='pool'),
    path('garscube/', views.garscube, name='garscube'),
    path('macpherson/', views.macpherson, name='macpherson'),
]

gucc_app/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

class Position(models.TextChoices):
    COMMODORE = 'Commodore', _('Commodore')
    SECRETARY = 'Secretary', _('Secretary')
    TREASURER = 'Treasurer', _('Treasurer')
    TRIP = 'Trip', _('Trip')
    SOCIAL = 'Social', _('Social')
    DEVELOPMENT = 'Development', _('Development')
    PUBLICITY = 'Publicity', _('Publicity')
    WELFARE = 'Welfare', _('Welfare')
    SHIPWRIGHT = 'Shipwright', _('Shipwright')
    COMPETITION = 'Competition', _('Competition')
    SAFETY = 'Safety', _('Safety')

class SML(models.TextChoices):
    S = 'S', _('Small')
    M = 'M', _('Medium')
    L = 'L', _('Large')

class Helmet(models.Model):
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=20,default="Palm")
    size = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.L
    )
    colour = models.CharField(max_length=20, default="Yellow")

class Kayak(models.Model):
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=20, default="Creaker")
    size = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.L
    )
    colour = models.CharField(max_length=20, default="Black")
    hasairbags = models.BooleanField(default=False, blank=True)
    slot = models.PositiveIntegerField(default=0, blank=True)

class Paddle(models.Model):
    id = models.AutoField(primary_key=True)
    feather = models.IntegerField(default=45)
    material = models.CharField(max_length=20, default="Carbon")
    size = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.L
    )
    righthanded = models.BooleanField(default=True)
    group = models.CharField(default="none", max_length=20) #enum??

class BA(models.Model):
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=10, default="Polo") # enum polo river
    maincolour = models.CharField(max_length=20, default="Yellow")
    innercolour = models.CharField(max_length=20, default="Black") # nullable
    number = models.PositiveIntegerField(default=0) # nullable
    size = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.M
    )


class Spraydeck(models.Model):
    id = models.AutoField(primary_key=True)
    decksize = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.L
    )
    waistsize = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.L
    )

class Ball(models.Model):
    id = models.AutoField(primary_key=True)
    size = models.IntegerField(default=5)

class Wetsuit(models.Model):
    id = models.AutoField(primary_key=True)
    size = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.M
    )

class Miscellaneous(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(default="random", max_length=30)
    description = models.TextField(default="")
    # type (throw line, sling, other)


class Pool(models.Model):
    helmets = models.ManyToManyField(Helmet)
    kayaks = models.ManyToManyField(Kayak)
    paddles = models.ManyToManyField(Paddle)
    bas = models.ManyToManyField(BA)
    spraydecks = models.ManyToManyField(Spraydeck)
    balls = models.ManyToManyField(Ball)
    miscellaneous = models.ManyToManyField(Miscellaneous)

class Garscube(models.Model):
    helmets = models.ManyToManyField(Helmet)
    kayaks = models.ManyToManyField(Kayak)
    paddles = models.ManyToManyField(Paddle)
    bas = models.ManyToManyField(BA)
    spraydecks = models.ManyToManyField(Spraydeck)
    wetsuits = models.ManyToManyField(Wetsuit)
    miscellaneous = models.ManyToManyField(Miscellaneous)


class MacPherson(models.Model):
    helmets = models.ManyToManyField(Helmet)
    kayaks = models.ManyToManyField(Kayak)
    paddles = models.ManyToManyField(Paddle)
    bas = models.ManyToManyField(BA)
    spraydecks = models.ManyToManyField(Spraydeck)
    balls = models.ManyToManyField(Ball)
    wetsuits = models.ManyToManyField(Wetsuit)
    miscellaneous = models.ManyToManyField(Miscellaneous)

class Store(models.Model):
    name = models.CharField(max_length=50)
    colour = models.CharField(max_length=10)
    description = models.TextField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        verbose_name = 'Store'
        verbose_name_plural = 'Stores'

class Committee(models.Model):
    position = models.CharField(
        max_length=20,
        choices=Position.choices,
        default=Position.COMMODORE,
    )
    blurb = models.TextField()
    img = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=20)

    def __str__(self):
        return f"Record {self.position}"

gucc_app/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Garscube, Store, Pool, Committee, Helmet, Kayak, Paddle, BA, Spraydeck, Ball, Miscellaneous
from django.urls import reverse
from django.db import models
# Create your views here.
def index(request):
    return render(request, 'gucc_app/index.html')

def about(request):
    return render(request, 'gucc_app/about.html')

def events(request):    
    return render(request, 'gucc_app/events.html')

def gallery(request):    
    return render(request, 'gucc_app/gallery.html')   

def main_shed(request):     
    return render(request, 'gucc_app/main-shed.html')

def macpherson_shed(request):
    return render(request, 'gucc_app/macpherson-shed.html')

def profile(request):
    return render(request, 'gucc_app/profile.html')

def login(request):  
    context_dict = {'loop':range(1000)} 
    return render(request, 'gucc_app/login.html', context=context_dict)   

def register(request):
    context_dict = {'loop':range(1000)} 
    return render(request, 'gucc_app/register.html', context=context_dict)

def logout(request):    
    return render(request, 'gucc_app/logout.html')

def koalas(request):    
    return render(request, 'gucc_app/koalas.html')

def basekit(request):    
    return render(request, 'gucc_app/includes/basekit.html')

def kayakkit(request):    
    return render(request, 'gucc_app/includes/kayakkit.html')

def baseinventory(request):
    return render(request, 'gucc_app/baseinventory.html')

def test(request):
    return render(request, 'gucc_app/test.html')  

def committee(request):
    committee = Committee.objects.all()
    return render(request, 'gucc_app/committee.html', {'committee': committee})

def welfare(request):
    return render(request, 'gucc_app/welfare.html')

def pool(request):
    pool = Pool.objects.first()

    store = get_object_or_404(Store, name='Pool')

    otherstores = Store.objects.exclude(name='Pool')

    kittypes = [field.name for field in Pool._meta.get_fields() if isinstance(field, models.ManyToManyField)]

    kitheaders = {
        'helmets': ['Id', 'Size', 'Colour', 'Type'],
        'kayaks': ['Id', 'Type', 'Size', 'Colour', 'Slot'],
        'paddles': ['Id', 'Feather', 'Material', 'Group', 'Size', 'RightHanded'],
        'bas': ['Type', 'MainColour', 'InnerColour', 'Number', 'Size'],
        'spraydecks': ['Id', 'DeckSize', 'WaistSize'],
        'balls': ['Id', 'Size'],
        'miscellaneous': ['Id', 'Description']
    }

    context = {
        'storetype': pool,
        'kittypes': kittypes,
        'kitheaders': {kittype: kitheaders.get(kittype, []) for kittype in kittypes},
        'store': store,
        'otherstores': otherstores
    }

    # Render the template with the context
    return render(request, 'gucc_app/pool.html', context) 

def garscube(request):
    garscube = Garscube.objects.first()

    store = get_object_or_404(Store, name='Garscube')

    otherstores = Store.objects.exclude(name='Garscube')

    kittypes = [field.name for field in Garscube._meta.get_fields() if isinstance(field, models.ManyToManyField)]

    kitheaders = {
        'helmets': ['Id', 'Size', 'Colour', 'Type'],
        'kayaks': ['Id', 'Type', 'Size', 'Colour', 'Slot'],
        'paddles': ['Id', 'Feather', 'Material', 'Group', 'Size', 'RightHanded'],
        'bas': ['Type', 'MainColour', 'InnerColour', 'Number', 'Size'],
        'spraydecks': ['Id', 'DeckSize', 'WaistSize'],
        'wetsuits': ['Id', 'Size'],
        'miscellaneous': ['Id', 'Description']
    }

    context = {
        'storetype': garscube,
        'kittypes': kittypes,
        'kitheaders': {kittype: kitheaders.get(kittype, []) for kittype in kittypes},
        'store': store,
        'otherstores': otherstores
    }

    # Render the template with the context
    return render(request, 'gucc_app/pool.html', context) 

def macpherson(request):
    return render(request, 'gucc_app/macpherson.html')

gucc_app/templates/gucc_app/includes/baseinventory.html
{% load static tailwind_tags custom_filters %}
{% tailwind_css %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet" id="fontawesome-css">
    <style>
        /* rounds the bottom of the tables cos table rows are dorks who dont want to be rounded */
        tr:last-child td:first-child { border-bottom-left-radius: 10px; }
        tr:last-child td:last-child { border-bottom-right-radius: 10px; }
    </style>
    <script src="{% static 'js/baseinventory.js' %}" defer></script>
</head>

{% include './navbar.html' %}

{% if store %}
    {% with storetextcolour='text-'|addstr:store.colour|addstr:'-600' %}
    <!-- DO NOT REMOVE THE BELOW COMMENT OR THE COLOURS WILL BREAK -->
    <!-- text-violet-600 text-red-600 text-yellow-600 text-green-600 -->
    <!-- its cos of tailwind needing to be able to have pre parsed the classes -->
    <h1 class="sm:hidden text-3xl font-bold text-center m-4 {{ storetextcolour }}">Pool Store</h1>
        <div class="grid grid-cols-3 m-4 text-center items-center flex-wrap">
            <div class="">
                {% include './storageselector.html' %}
            </div>
            <h1 class="hidden sm:grid text-4xl font-bold {{ storetextcolour }}">
                {{ store.name }}
            </h1>
            <div class="justify-self-end col-start-3 {{ storetextcolour }}">
                <button id="togglefish" class="border-black border-2 rounded-2xl px-4 h-full">
                    <h1 class="text-2xl font-bold">Filters</h1>
                </button>
            </div>
        </div>
    {% endwith %}
{% endif %}

<div id="filters" class="hidden">
    {% if kittypes %}
        {% with numkits=kittypes|length %}
            {% with colsnum='md:grid-cols-'|addstr:numkits %}
            <!-- md:grid-cols-7  md:grid-cols-8 md:grid-cols-9 -->
            <div class="grid grid-cols-3 {{ colsnum }} text-sm md:text-base gap-4 p-4">
            {% if store %}
                {% with storebgcolour='bg-'|addstr:store.colour|addstr:'-600' %}
                    <!-- bg-violet-600 bg-yellow-600 bg-red-600 bg-green-600 -->
                    {% for kit in kittypes %}
                        <button class="filter-btn {{storebgcolour}} border border-black font-semibold py-2 px-4 rounded-lg hover:cursor-pointer " data-kit="{{ kit }}">{{ kit }}</button>
                    {% endfor %}
                {% endwith %}
            {% endif %}
            </div>
            {% endwith %}
        {% endwith %}
    {% endif %}
            </div>


<div class="grid sm:grid-cols-2 sm:text-sm md:grid-cols-3 lg:text-lg justify-items-center [&_div]:border-black [&>div]:border-2 [&>div]:m-2 [&>div]:rounded-xl gap-y-10">
    {% if kittypes %}
        {% for kit in kittypes %}
            <div id="{{ kit }}-tablediv" class="text-center mx-auto w-[85%] overflow-x-scro">
                <h2 class="text-2xl mb-2 font-mono">{{ kit|capfirst }}</h2>
                <table id="table-{{ kit }}" class="min-w-full rounded-full px-2">
                    <thead>
                        <tr class="bg-blue-400 border-b-2 border-t-2 border-black max-w-full">
                            {% get_kitheaders kitheaders kit as headers %}
                            {% for header in headers %}
                                <th class="sortable-header max-w-full py-2">{{ header }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody class="rounded text-center">
                        {% get storetype kit as items %}
                        {% for item in items %}
                            <tr class="even:bg-pink-200 odd:bg-pink-400 rounded-b-full">
                                {% for header in headers %}
                                    <td class="py-2">{{ item|get_field_value:header }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endfor %}
    {% endif %}
</div>

gucc_app/templates/gucc_app/includes/basekit.html
<div id="kit-container" class="bg-pink-400 rounded-full px-2 grid grid-cols-4 justify-items-center m-2">
    {% for key, value in kit.items %}
        <div id="kit" class="col-span-1">{{ value }}</div>
    {% endfor %}           
</div>

gucc_app/templates/gucc_app/includes/calendar.html
<!-- {% block title_block %} Google Calendar Events {% endblock %} -->
<!-- {% block content_block %} -->


<iframe src="https://embed.styledcalendar.com/#ugPXA9WyseE5xWU09kWw" title="Styled Calendar" class="styled-calendar-container p-10" style="width: 100%; border: none; overflow: hidden; height: 678px;" data-cy="calendar-embed-iframe" id="iFrameResizer0" scrolling="no"></iframe>
<script async="" type="module" src="https://embed.styledcalendar.com/assets/parent-window.js"></script>
<script src="/static/django-browser-reload/reload-listener.js" data-worker-script-path="/static/django-browser-reload/reload-worker.js" data-events-path="/__reload__/events/" defer=""></script>

<div id="c-notification" class="c-notification"><iframe id="c-iframe" title="c-iframe" class="c-iframe" allow="clipboard-read; clipboard-write" style="width: 0px; height: 0px; visibility: visible;"></iframe></div>
<!-- {% endblock %} -->

gucc_app/templates/gucc_app/includes/filter.html
<label class="block">
    <input type="checkbox" name="option" value="1" class="hidden peer">
    <div class="p-2 m-2 bg-emerald-300 border border-gray-300 rounded-lg cursor-pointer peer-checked:border-blue-500 peer-checked:bg-gray-400 text-center">
        <h3 class="text-lg font-medium text-gray-900">Option 1</h3>
    </div>
</label>

gucc_app/templates/gucc_app/includes/kayakkit.html
{% load static tailwind_tags %} 
{% tailwind_css %}

<div class="m-2 px-2 bg-red-600 rounded-t">
    <div class="rounded-full grid grid-cols-4 justify-items-center">
        <button id="filter1" class="col-span-1 bg-red-600" data-target="para1">filter1</button>
        <button id="filter2" class="col-span-1" data-target="para2">filter2</button>
        <button id="filter3" class="col-span-1" data-target="para3">filter3</button>
        <button id="filter4" class="col-span-1" data-target="para4">filter4</button>           
    </div>

    <div class="grid grid-cols-7">
        {% for i in "abcdefg" %}
            {% include './filter.html' %}
        {% endfor %}

        <p id="para1" class="hidden">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor quisquam, doloribus quasi, odio laboriosam laudantium minima architecto aperiam veritatis amet libero cumque, eveniet enim? Sed veritatis aut beatae ipsa animi?</p>
        <p id="para2" class="hidden">Paragraph 2 content goes here.</p>
        <p id="para3" class="hidden">Paragraph 3 content goes here.</p>
        <p id="para4" class="hidden">Paragraph 4 content goes here.</p>
    </div>
</div>



<script>
    document.querySelectorAll('button').forEach(button => {
    button.addEventListener('click', function() {
        // Hide all paragraphs
        document.querySelectorAll('p').forEach(p => p.classList.add('hidden'));

        // Show the target paragraph
        var targetId = this.getAttribute('data-target');
        var targetElement = document.getElementById(targetId);
        targetElement.classList.remove('hidden');
    });
}); 
</script>

gucc_app/templates/gucc_app/includes/navbar.html
{% load static %}
<head>
    <style>
        .dropdown-content {
            margin-bottom: 10rem; /* Adjust the margin as needed */
        }
    </style>

<script src="{% static 'js/navbar.js' %}" defer></script>
</head>

<header>
    <nav class="bg-gray-800 text-gray-300 font-medium text-sm">
        <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
            <div class="relative flex items-center justify-between h-16 hover:[&_a]:bg-gray-700 hover:[&_a]:text-white">
                <div class="absolute inset-y-0 left-0 flex items-center md:hidden">
                    <!-- Mobile menu button-->
                    <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false" id="mobile-menu-button">
                        <span class="sr-only">Open main menu</span>
                        <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"/>
                        </svg>
                        <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
                        </svg>
                    </button>
                </div>
                <div class="flex-1 flex items-center justify-center md:items-stretch md:justify-start">
                    <a href="{% url 'gucc_app:index' %}" class="flex-shrink-0 d-none d-lg-inline-block">
                        <img class="h-10 w-auto" src="{% static 'images/canoe_club_logo.jpg' %}" alt="logo">
                    </a>
                    <div class="hidden md:block md:ml-6">
                        <div class="flex space-x-4">
                            <a href="{% url 'gucc_app:index' %}" class=" px-3 py-2 rounded-md">Home</a>

                            <div class="dropdown relative inline-block text-center">
                                <button class="dropbtn hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md inline-flex items-center cursor-pointer">
                                    About
                                    <svg class="ml-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
                                    </svg>
                                </button>
                                <div class="dropdown-content absolute hidden bg-gray-800 pt-1 w-full *:block *:px-2 *:py-2 z-50">
                                    <a href="{% url 'gucc_app:about' %}" class="">
                                        About Us
                                    </a>
                                    <a href="{% url 'gucc_app:committee' %}" class="">
                                        Committee
                                    </a>
                                    <a href="{% url 'gucc_app:welfare' %}" class="">
                                        Welfare
                                    </a>
                                </div>
                            </div>

                            <!-- <a href="{% url 'gucc_app:events' %}" class=" px-3 py-2 rounded-md">Events</a> -->
                            <a href="{% url 'gucc_app:gallery' %}" class=" px-3 py-2 rounded-md">Gallery</a>
                            
                            <div class="dropdown relative inline-block text-center">
                                <button class="dropbtn hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md inline-flex items-center cursor-pointer">
                                    Inventory
                                    <svg class="ml-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
                                    </svg>
                                </button>
                                <div class="dropdown-content absolute hidden bg-gray-800 pt-1 w-full *:block *:px-2 *:py-2 z-50">
                                    <a href="{% url 'gucc_app:garscube' %}" class="">
                                        Garscube
                                    </a>
                                    <a href="{% url 'gucc_app:macpherson' %}" class="">
                                        MacPherson
                                    </a>
                                    <a href="{% url 'gucc_app:pool' %}" class="">
                                        Pool Cupboard
                                    </a>
                                </div>
                            </div>       

                        </div>
                    </div>
                </div>
                <div class="absolute inset-y-0 right-0 flex items-center pr-2 md:static md:inset-auto md:ml-6 md:pr-0">
                    <div class="flex space-x-4">
                        <div class="hidden md:block">
                            {% if user.is_authenticated %}
                                <a href="{% url 'gucc_app:logout' %}" class=" px-3 py-2 rounded-md">Logout</a>
                            {% else %}
                                <a href="{% url 'gucc_app:login' %}" class=" px-3 py-2 rounded-md">Login</a>
                            {% endif %}
                        </div>
                        <div>
                            <a href="https://www.facebook.com/profile.php?id=1.000542e+14" target="_blank" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </div>
                        <div>
                            <a href="https://www.instagram.com/gusacanoe?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" target="_blank" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </div>
                        <div>
                            <a href="https://github.com/likahey99/gucc_website" target="_blank" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md">
                                <i class="fab fa-github"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="md:hidden hidden bg-slate-400 text-gray-700" id="mobile-menu">
        <div class="px-2 pt-2 pb-3 space-y-1 text-base">
            <a href="{% url 'gucc_app:index' %}" class="block px-3 py-2 rounded-md">Home</a>

            <div class="dropdown relative inline-block text-center z-50">
                <button class="dropbtn hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md inline-flex items-center cursor-pointer">
                    About
                    <svg class="ml-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
                    </svg>
                </button>
                <div class="dropdown-content absolute hidden bg-gray-800 pt-1 w-full *:block *:px-2 *:py-2 text-white z-50">
                    <a href="{% url 'gucc_app:about' %}" class="">
                        About Us
                    </a>
                    <a href="{% url 'gucc_app:committee' %}" class="">
                        Committee
                    </a>
                    <a href="{% url 'gucc_app:welfare' %}" class="">
                        Welfare
                    </a>
                </div>
            </div>
            
            <!-- <a href="{% url 'gucc_app:events' %}" class="block px-3 py-2 rounded-md">Events</a> -->
            <a href="{% url 'gucc_app:gallery' %}" class="block px-3 py-2 rounded-md">Gallery</a>

            <div class="dropdown relative inline-block text-center">
                <button class="dropbtn hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md inline-flex items-center cursor-pointer">
                    Inventory
                    <svg class="ml-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
                    </svg>
                </button>
                <div class="dropdown-content absolute hidden bg-gray-800 pt-1 w-full *:block *:px-2 *:py-2 text-white z-50">
                    <a href="garscube" class="">
                        Garscube Storage
                    </a>
                    <a href="{% url 'gucc_app:macpherson' %}" class="">
                        MacPherson Shed
                    </a>
                    <a href="{% url 'gucc_app:pool' %}" class="">
                        Pool Cupboard
                    </a>
                </div>
            </div>      

            <a href="{% url 'gucc_app:login' %}" class="block px-3 py-2 rounded-md">Login</a>
        </div>
    </div>
</header>

gucc_app/templates/gucc_app/includes/storageselector.html
{% load static tailwind_tags custom_filters %}
{% tailwind_css %}

<div class="container first:border border-black border-2 text-base sm:text-lg text-center w-full sm:w-[70%] md:w-[60%] lg:w-1/2 rounded-2xl">
    <div class="grid grid-rows-2">
        {% if otherstores %}
        {% for otherstore in otherstores %}
            {% with storecolour='text-'|addstr:otherstore.colour|addstr:'-600' %}
            {% if otherstore.name == "Pool" %}
                <a href="{% url 'gucc_app:pool' %}" class="{{ storecolour }}">
                    <button class="font-bold {{ storecolour }}">{{ otherstore.name }}</button>
                </a>
            {% elif otherstore.name == "Garscube" %}
                <a href="{% url 'gucc_app:garscube' %}" class="{{ storecolour }}">
                    <button class="font-bold {{ storecolour }}">{{ otherstore.name }}</button>
                </a>
            {% elif otherstore.name == "Repair" %}
                <a href="{% url 'gucc_app:macpherson' %}" class="{{ storecolour }}">
                <button class="font-bold {{ storecolour }}">{{ otherstore.name }}</button>
            </a>
        {% endif %}
            {% endwith %}
        {% endfor %}
        {% endif %}
    </div>
</div>