gucc/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include,path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('gucc_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gucc_app/urls.py
from django.urls import path

from . import views

app_name = 'gucc_app'   

urlpatterns = [
    path('', views.index, name='index'), 
    path('about/', views.about, name='about'),
    path('committee/', views.committee, name='committee'),
    path('welfare', views.welfare, name='welfare'),
    path('events/', views.events, name='events'),
    path('gallery/', views.gallery, name='gallery'),
    path('main-shed/', views.main_shed, name='main_shed'),
    path('macpherson-shed/', views.macpherson_shed, name='macpherson_shed'),
    path('profile/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('koalas/', views.koalas, name='koalas'),
    path('basekit/', views.basekit, name='basekit'),
    path('kayakkit/', views.kayakkit, name='kayakkit'),
    path('baseinventory/', views.baseinventory, name='baseinventory'),
    path('test/', views.test, name='test'),
    path('pool/', views.pool, name='pool'),
    path('garscube/', views.garscube, name='garscube'),
    path('macpherson/', views.macpherson, name='macpherson'),
]

gucc_app/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

class Position(models.TextChoices):
    COMMODORE = 'Commodore', _('Commodore')
    SECRETARY = 'Secretary', _('Secretary')
    TREASURER = 'Treasurer', _('Treasurer')
    TRIP = 'Trip', _('Trip')
    SOCIAL = 'Social', _('Social')
    DEVELOPMENT = 'Development', _('Development')
    PUBLICITY = 'Publicity', _('Publicity')
    WELFARE = 'Welfare', _('Welfare')
    SHIPWRIGHT = 'Shipwright', _('Shipwright')
    COMPETITION = 'Competition', _('Competition')
    SAFETY = 'Safety', _('Safety')

class SML(models.TextChoices):
    S = 'S', _('Small')
    M = 'M', _('Medium')
    L = 'L', _('Large')

class Helmet(models.Model):
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=20,default="Palm")
    size = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.L
    )
    colour = models.CharField(max_length=20, default="Yellow")

class Kayak(models.Model):
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=20, default="Creaker")
    size = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.L
    )
    colour = models.CharField(max_length=20, default="Black")
    hasairbags = models.BooleanField(default=False, blank=True)
    slot = models.PositiveIntegerField(default=0, blank=True)

class Paddle(models.Model):
    id = models.AutoField(primary_key=True)
    feather = models.IntegerField(default=45)
    material = models.CharField(max_length=20, default="Carbon")
    size = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.L
    )
    righthanded = models.BooleanField(default=True)
    group = models.CharField(default="none", max_length=20) #enum??

class BA(models.Model):
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=10, default="Polo") # enum polo river
    maincolour = models.CharField(max_length=20, default="Yellow")
    innercolour = models.CharField(max_length=20, default="Black") # nullable
    number = models.PositiveIntegerField(default=0) # nullable
    size = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.M
    )


class Spraydeck(models.Model):
    id = models.AutoField(primary_key=True)
    decksize = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.L
    )
    waistsize = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.L
    )

class Ball(models.Model):
    id = models.AutoField(primary_key=True)
    size = models.IntegerField(default=5)

class Wetsuit(models.Model):
    id = models.AutoField(primary_key=True)
    size = models.CharField(
        max_length=1,
        choices=SML.choices,
        default=SML.M
    )

class Miscellaneous(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(default="random", max_length=30)
    description = models.TextField(default="")
    # type (throw line, sling, other)


class Pool(models.Model):
    helmets = models.ManyToManyField(Helmet)
    kayaks = models.ManyToManyField(Kayak)
    paddles = models.ManyToManyField(Paddle)
    bas = models.ManyToManyField(BA)
    spraydecks = models.ManyToManyField(Spraydeck)
    balls = models.ManyToManyField(Ball)
    miscellaneous = models.ManyToManyField(Miscellaneous)

class Garscube(models.Model):
    helmets = models.ManyToManyField(Helmet)
    kayaks = models.ManyToManyField(Kayak)
    paddles = models.ManyToManyField(Paddle)
    bas = models.ManyToManyField(BA)
    spraydecks = models.ManyToManyField(Spraydeck)
    wetsuits = models.ManyToManyField(Wetsuit)
    miscellaneous = models.ManyToManyField(Miscellaneous)


class MacPherson(models.Model):
    helmets = models.ManyToManyField(Helmet)
    kayaks = models.ManyToManyField(Kayak)
    paddles = models.ManyToManyField(Paddle)
    bas = models.ManyToManyField(BA)
    spraydecks = models.ManyToManyField(Spraydeck)
    balls = models.ManyToManyField(Ball)
    wetsuits = models.ManyToManyField(Wetsuit)
    miscellaneous = models.ManyToManyField(Miscellaneous)

class Store(models.Model):
    name = models.CharField(max_length=50)
    colour = models.CharField(max_length=10)
    description = models.TextField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        verbose_name = 'Store'
        verbose_name_plural = 'Stores'

class Committee(models.Model):
    position = models.CharField(
        max_length=20,
        choices=Position.choices,
        default=Position.COMMODORE,
    )
    blurb = models.TextField()
    img = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=20)

    def __str__(self):
        return f"Record {self.position}"

gucc_app/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Garscube, Store, Pool, Committee, Helmet, Kayak, Paddle, BA, Spraydeck, Ball, Miscellaneous
from django.urls import reverse
from django.db import models
# Create your views here.
def index(request):
    return render(request, 'gucc_app/index.html')

def about(request):
    return render(request, 'gucc_app/about.html')

def events(request):    
    return render(request, 'gucc_app/events.html')

def gallery(request):    
    return render(request, 'gucc_app/gallery.html')   

def main_shed(request):     
    return render(request, 'gucc_app/main-shed.html')

def macpherson_shed(request):
    return render(request, 'gucc_app/macpherson-shed.html')

def profile(request):
    return render(request, 'gucc_app/profile.html')

def login(request):  
    context_dict = {'loop':range(1000)} 
    return render(request, 'gucc_app/login.html', context=context_dict)   

def register(request):
    context_dict = {'loop':range(1000)} 
    return render(request, 'gucc_app/register.html', context=context_dict)

def logout(request):    
    return render(request, 'gucc_app/logout.html')

def koalas(request):    
    return render(request, 'gucc_app/koalas.html')

def basekit(request):    
    return render(request, 'gucc_app/includes/basekit.html')

def kayakkit(request):    
    return render(request, 'gucc_app/includes/kayakkit.html')

def baseinventory(request):
    return render(request, 'gucc_app/baseinventory.html')

def test(request):
    return render(request, 'gucc_app/test.html')  

def committee(request):
    committee = Committee.objects.all()
    return render(request, 'gucc_app/committee.html', {'committee': committee})

def welfare(request):
    return render(request, 'gucc_app/welfare.html')

def pool(request):
    pool = Pool.objects.first()

    store = get_object_or_404(Store, name='Pool')

    otherstores = Store.objects.exclude(name='Pool')

    kittypes = [field.name for field in Pool._meta.get_fields() if isinstance(field, models.ManyToManyField)]

    kitheaders = {
        'helmets': ['Id', 'Size', 'Colour', 'Type'],
        'kayaks': ['Id', 'Type', 'Size', 'Colour', 'Slot'],
        'paddles': ['Id', 'Feather', 'Material', 'Group', 'Size', 'RightHanded'],
        'bas': ['Type', 'MainColour', 'InnerColour', 'Number', 'Size'],
        'spraydecks': ['Id', 'DeckSize', 'WaistSize'],
        'balls': ['Id', 'Size'],
        'miscellaneous': ['Id', 'Description']
    }

    context = {
        'storetype': pool,
        'kittypes': kittypes,
        'kitheaders': {kittype: kitheaders.get(kittype, []) for kittype in kittypes},
        'store': store,
        'otherstores': otherstores
    }

    # Render the template with the context
    return render(request, 'gucc_app/pool.html', context) 

def garscube(request):
    garscube = Garscube.objects.first()

    store = get_object_or_404(Store, name='Garscube')

    otherstores = Store.objects.exclude(name='Garscube')

    kittypes = [field.name for field in Garscube._meta.get_fields() if isinstance(field, models.ManyToManyField)]

    kitheaders = {
        'helmets': ['Id', 'Size', 'Colour', 'Type'],
        'kayaks': ['Id', 'Type', 'Size', 'Colour', 'Slot'],
        'paddles': ['Id', 'Feather', 'Material', 'Group', 'Size', 'RightHanded'],
        'bas': ['Type', 'MainColour', 'InnerColour', 'Number', 'Size'],
        'spraydecks': ['Id', 'DeckSize', 'WaistSize'],
        'wetsuits': ['Id', 'Size'],
        'miscellaneous': ['Id', 'Description']
    }

    context = {
        'storetype': garscube,
        'kittypes': kittypes,
        'kitheaders': {kittype: kitheaders.get(kittype, []) for kittype in kittypes},
        'store': store,
        'otherstores': otherstores
    }

    # Render the template with the context
    return render(request, 'gucc_app/pool.html', context) 

def macpherson(request):
    return render(request, 'gucc_app/macpherson.html')

gucc_app/templates/gucc_app/about.html
{% extends "gucc_app/base.html" %}
{% load static %}


{% block title_block %}
    About
{% endblock %}

{% block content_block %}
<div class="container mx-auto pt-4">
    <div class="grid grid-cols-1 gap-4">
        <!-- First item -->
        <div class="flex flex-col md:flex-row items-center p-4 bg-white shadow-md rounded-lg">
            <div class="md:w-1/2 p-2">
                <h2 class="text-center font-bold text-xl text-blue-400 mb-4">Main About</h2>
                <p>A key part of being a member of GUCC is getting out and about on weekends for paddling and fun. We run a wide range of both day and weekend long trips exploring all corners of Scotland near and far. Our trips should happen every 2nd weekend and we make sure to paddle a variety of different rivers to cater for all standards of paddlers. Whether you’re the freshest of freshers or a long-time big sender you’ll be able to have fun and push yourself on a GUCC trip.</p> 
        
                <!-- <p>INTERMEDIATE WEEKEND is a great chance to get acquainted with some of Scotlands slightly spicier and harder rivers. If you’re a more confident paddler and looking to shred some Gnarr and push yourself then this is the trip for you. Just like our other weekend trips there is plenty of fun and games to be had in the evenings once paddling is over for the day.</p> -->
           </div>
            <div class="md:w-1/2 p-2">
                <img src="{% static 'images/canoe_club_photo_2024.jpg' %}" alt="Picture 1" class="w-full h-auto rounded-lg">
            </div>
        </div>
        <!-- Second item -->
        <div class="flex flex-col md:flex-row-reverse items-center p-4 bg-white shadow-md rounded-lg">
            <div class="md:w-1/2 p-2">
                <h2 class="text-center font-bold text-xl text-pink-400 mb-4">About Socials</h2>
                <p class="text-lg font-semibold mb-2">Text for the Socials</p>
            </div>
            <div class="md:w-1/2 p-2">
                <img src="{% static 'images/social.jpg' %}" alt="Picture 2" class="w-full h-auto rounded-lg">
            </div>
        </div>
        <!-- Third item -->
        <div class="flex flex-col md:flex-row items-center p-4 bg-white shadow-md rounded-lg">
            <div class="md:w-1/2 p-2">
                <h2 class="text-center font-bold text-xl text-green-800 mb-4">About Trips</h2>
                <p> first weekend trip of the year is FRESHERS WEEKEND, this trip is catered towards our newer members and will allow you to get comfortable in a boat in a beginner friendly environment with help and coaching from our friendly older members. There are also plenty of social activities in the evening for everyone to get to know each other and feel included in the GUCC family.</p> The annual surf trip to beautiful MACHRIHANISH on the west coast is a highlight of the GUCC year. Prepare for exhilarating surfing and swimming by day and partying hard by night! As one of our more ‘seshy’ weekends we cannot guarantee that your liver will be happy by the end but your heart and soul certainly will.</p>
            </div>
            <div class="md:w-1/2 p-2">
                <img src="{% static 'images/river_trip.jpg' %}" alt="Picture 3" class="w-full h-auto rounded-lg">
            </div>
        </div>
        <h1>However many abouts you want. Could do a polo or general competitions one.</h1>
    </div>
</div>
{% endblock %}

gucc_app/templates/gucc_app/base.html
{% load static tailwind_tags %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> {% block title_block %} GUCC {% endblock %} </title>
        <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet" id="fontawesome-css">
        {% tailwind_css %}
        {% block head_block %}
            <!-- empty -->
        {% endblock %}
        <script src="{% static 'js/domcontent.js' %}" defer></script>
    </head>

    <body class="pb-5">
        {% include './includes/navbar.html' %}
        {% block login_block %}
            <!-- empty -->
        {% endblock %}
        <div class="container mx-auto pt-4">
            {% block content_block %}
                <!-- empty -->
            {% endblock %}
        </div>
    </body>

</html> 

gucc_app/templates/gucc_app/committee.html
{% extends 'gucc_app/base.html' %}
{% load static tailwind_tags %}

{% block title_block %} Committee {% endblock %}

{% block head_block %}
{% endblock %}

{% block content_block %}
<div class="grid sm:grid-cols-2 sm:text-sm md:grid-cols-3 lg:text-lg justify-items-center [&_div]:border-black [&>div]:border-2 [&>div]:m-2 [&>div]:rounded-xl p-4 gap-10">
    {% if committee %}
    {% for member in committee %}
    <div class="py-2 min-w-[75%]">
        <h1 class="text-center font-bold text-3xl text-blue-700 border-black border-b-2 pb-2">{{ member.get_position_display }}</h1>
        <h2 class="text-center font-bold text-2xl p-1">{{ member.name }}</h2>
        <img class="mx-auto" src="{{ member.img.url }}" alt="image">
        <p class="md:text-sm p-1 text-center">
            {{ member.blurb }}
        </p>
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

gucc_app/templates/gucc_app/events.html
{% extends 'gucc_app/base.html' %}
{% load static tailwind_tags %}

{% block title_block %} Events {% endblock %}

{% block head_block %}
{% endblock %}

{% block content_block %}
    <h1 class="text-4xl text-center mt-8">Here you can find out more about our events</h1>

    {% include './includes/calendar.html' %}

    <!-- https://www.reddit.com/r/css/comments/buwtof/styling_an_embedded_google_calendar_beginner/ -->
    <p>This is basically a clone of Home rn. I think having the calendar on home is the right idea
        but this page is also the right thing imo. On here we can have a bit more info about the events 
        as well as links to other sites with more information.
    </p>
{% endblock %}

gucc_app/templates/gucc_app/garscube.html
{% load static tailwind_tags custom_filters %}
{% tailwind_css %}

{% include 'gucc_app/includes/baseinventory.html' %}

gucc_app/templates/gucc_app/index.html
{% extends 'gucc_app/base.html' %}
{% load static tailwind_tags %}

{% block title_block %} Home {% endblock %}

{% block head_block %}
{% endblock %}

{% block content_block %}
    <div style="background-color: rgba(51, 150, 248, 0.69);" class="p-4 m-0 text-center rounded-t-full align-middle">
        <h1 class="text-4xl text-center font-mono font-semibold ">Welcome to GUCC</h1>
    </div>
    <div class="md:grid grid-cols-2">
        <img class="mx-auto h-full" src="{% static 'images/liz_nesk.jpg' %}" alt="coolRiverPic">
        <img class="mx-auto h-full" src="{% static 'images/kai_nesk.jpg' %}" alt="coolRiverPic">
    </div>
        <div class="col-span-2" style="background: rgba(51, 150, 248, 0.69);">
            <div class="col-span-2 text-base font-semibold pb-2">
                <p class="text-center">Welcome to the Glasgow Uni Canoe Club!</p>
                <p class="text-center">We are an inclusive kayaking club for all skill levels!</p>
                <p class="text-center">We meet weekly to improve our kayaking skills, but more importantly to have fun</p>
                <p class="text-center">We have a session in the uni pool every thursday followed up by FREE PIZZA and good vibes in bank street kitchen</p>
                <p class="text-center">We also organise kayak trips and events across scotland to rivers, events and more!</p>
                <p class="text-center">Come join us if you are a kayaking pro sending grade 5s or if you have never been in a kayak before (I hadn't!) </p>
            </div>
        </div>
        {% include './includes/calendar.html' %}
        <!-- https://www.reddit.com/r/css/comments/buwtof/styling_an_embedded_google_calendar_beginner/ -->

{% endblock %}

gucc_app/templates/gucc_app/login.html
{% load static tailwind_tags %}
{% include './includes/navbar.html' %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> {% block title_block %} GUCC {% endblock %} </title>
        <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet" id="fontawesome-css">
        {% tailwind_css %}
        {% block head_block %}
            <!-- empty -->
        {% endblock %}
    </head>
<!-- component -->

<section class = "body bg-white dark:bg-[#0F172A] p-0 m-0">
    <div class = "bg-black before:animate-pulse before:bg-gradient-to-b before:from-gray-900 overflow-hidden before:via-[#00FF00] before:to-gray-900 before:absolute ">
        <div id="myDIV" >
            <div class = "w-[100vw] h-[100vh] px-3 sm:px-5 flex items-center justify-center absolute">
                <div class = "w-full sm:w-1/2 lg:2/3 px-6 bg-gray-500 bg-opacity-20 bg-clip-padding backdrop-filter backdrop-blur-sm text-white z-50 py-4  rounded-lg">
                    <div class = "w-full flex justify-center text-cyan-400 text-xl mb:2 md:mb-5">
                        Sign In
                    </div>
                    <div class="mb-6">
                        <label for="email" class="block mb-2 text-xs font-medium text-white">Your email</label>
                        <input type="email" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 text-xs rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-1.5 md:p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="1hr30@spentonthis.com" required>
                    </div>
                    <div class="mb-6">
                        <label for="password" class="block mb-2 text-xs font-medium text-white">Your password</label>
                        <input type="password" id="password" class="bg-gray-50 border border-gray-300 text-gray-900 text-xs rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-1.5 md:p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required>
                    </div>
                    <div class = "flex flex-row justify-between">
                        <div class = "text-white text-sm md:text-md ">Forgot Password</div>
                        <div class = "text-cyan-400 text-sm md:text-md">Register</div>
                    </div>
                    <div class = "mt-4 md:mt-10 w-full flex justify-center text-sm md:text-xl bg-cyan-400 py-2 rounded-md">
                        Login
                    </div>
        
                </div>
            </div>
            <div class="flex flex-wrap gap-0.5 h-screen items-center justify-center  relative">
                {% for i in loop %}
                    <div class = "transition-colors duration-[1.5s] hover:duration-[0s] border-[#00FF00] h-[calc(5vw-2px)] w-[calc(5vw-2px)] md:h-[calc(4vw-2px)] md:w-[calc(4vw-2px)] lg:h-[calc(3vw-4px)] lg:w-[calc(3vw-4px)] bg-gray-900 hover:bg-[#00FF00]"></div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

gucc_app/templates/gucc_app/pool.html
{% load static tailwind_tags custom_filters %}
{% tailwind_css %}

{% include 'gucc_app/includes/baseinventory.html' %} 

gucc_app/templates/gucc_app/register.html
{% load static tailwind_tags %}
{% include './includes/navbar.html' %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> {% block title_block %} GUCC {% endblock %} </title>
        <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet" id="fontawesome-css">
        {% tailwind_css %}
        {% block head_block %}
            <!-- empty -->
        {% endblock %}
    </head>
<!-- component -->

<section class = "body bg-white dark:bg-[#0F172A] p-0 m-0">
    <div class = "bg-black before:animate-pulse before:bg-gradient-to-b before:from-gray-900 overflow-hidden before:via-[#00FF00] before:to-gray-900 before:absolute ">
        <div id="myDIV" >
            <div class = "w-[100vw] h-[100vh] px-3 sm:px-5 flex items-center justify-center absolute">
                <div class = "w-full sm:w-1/2 lg:2/3 px-6 bg-gray-500 bg-opacity-20 bg-clip-padding backdrop-filter backdrop-blur-sm text-white z-50 py-4  rounded-lg">
                    <div class = "w-full flex justify-center text-purple-400 text-xl mb:2 md:mb-5">
                        Register
                    </div>
                    <div class="mb-6">
                        <label for="email" class="block mb-2 text-xs font-medium text-white">Your email</label>
                        <input type="email" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 text-xs rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-1.5 md:p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="1hr30@spentonthis.com" required>
                    </div>
                    <div class="mb-6">
                        <label for="password" class="block mb-2 text-xs font-medium text-white">Your password</label>
                        <input type="password" id="password" class="bg-gray-50 border border-gray-300 text-gray-900 text-xs rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-1.5 md:p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required>
                    </div>
                    <div class = "flex flex-row justify-between">
                        <div class = "text-white text-sm md:text-md ">Forgot Password</div>
                        <div class = "text-purple-400 text-sm md:text-md">Login</div>
                    </div>
                    <div class = "mt-4 md:mt-10 w-full flex justify-center text-sm md:text-xl bg-purple-400 py-2 rounded-md">
                        Register
                    </div>
        
                </div>
            </div>
            <div class="flex flex-wrap gap-0.5 h-screen items-center justify-center  relative">
                {% for i in loop %}
                    <div class = "transition-colors duration-[1.5s] hover:duration-[0s] border-[#00FF00] h-[calc(5vw-2px)] w-[calc(5vw-2px)] md:h-[calc(4vw-2px)] md:w-[calc(4vw-2px)] lg:h-[calc(3vw-4px)] lg:w-[calc(3vw-4px)] bg-gray-900 hover:bg-[#00FF00]"></div>
                {% endfor %}
            </div>
        </div>
    </div>
    
    <!-- <script>
        const para = document.createElement("div");
        para.className = 'flex flex-wrap gap-0.5 h-screen items-center justify-center  relative';
            let el = '<div class = "transition-colors duration-[1.5s] hover:duration-[0s] border-[#00FF00] h-[calc(5vw-2px)] w-[calc(5vw-2px)] md:h-[calc(4vw-2px)] md:w-[calc(4vw-2px)] lg:h-[calc(3vw-4px)] lg:w-[calc(3vw-4px)] bg-gray-900 hover:bg-[#00FF00]"></div>'
            for (var k = 1; k<=1000; k++){
                el+= '<div class = " transition-colors duration-[1.5s] hover:duration-[0s] border-[#00FF00] h-[calc(5vw-2px)] w-[calc(5vw-2px)] md:h-[calc(4vw-2px)] md:w-[calc(4vw-2px)] lg:h-[calc(3vw-4px)] lg:w-[calc(3vw-4px)] bg-gray-900 hover:bg-[#00FF00]"></div>';
            };
    
            para.innerHTML = el;
        document.getElementById("myDIV").appendChild(para);
    </script> -->
    
</section>

gucc_app/templates/gucc_app/welfare.html
{% extends 'gucc_app/base.html' %}
{% load static tailwind_tags %}

{% block title_block %} Committee {% endblock %}

{% block head_block %}
{% endblock %}

{% block content_block %}
<h1 class="text-3xl">WIP about welfare on and off the river with links to club welfare contact as well as gusa and external help providers</h1>
{% endblock %}